import fs from "fs";

const DEST = "c:/Users/erezg/Documents/Claude/Projects/Clarity Pack/.planning/research/SUMMARY.md";

const lines = [
"# Project Research Summary",
"",
"**Project:** Clarity Pack",
"**Domain:** Paperclip plugin — TypeScript/React multi-surface UI + heartbeat-driven Editor-Agent",
"**Researched:** 2026-05-07",
"**Confidence:** HIGH on stack pins and plugin contract (fetched directly from paperclipai/paperclip@master). MEDIUM on managed-agent contract and plugin-owned migrations (guide + working code support them; formal PLUGIN_SPEC.md is behind the implementation). See Conflicts section for items requiring SPEC.md resolution.",
"",
"---",
"",
"## Executive Summary",
"",
"Clarity Pack is a single npm package that integrates four user-facing surfaces and one managed agent into an unmodified Paperclip install by conforming strictly to the Paperclip plugin contract. The plugin system is architecturally mature: one manifest, one UI bundle exporting many named React components (the kitchen-sink example ships 13 contribution points from one package), one out-of-process worker over JSON-RPC stdio, and one Postgres schema namespace that is plugin-owned and additive-only. All four researchers independently confirmed this shape. There is no ambiguity about the top-level form factor.",
"",
"The recommended approach is to build inside-out: shared primitives first (src/shared/reference-resolver.ts and src/shared/blocker-chain.ts), then the Editor-Agent skeleton, then Reader view and Situation Room together in Phase 1, then Bulletin in Phase 2, then Employee Chat in Phase 3. This ordering is forced by data dependencies — both Phase 1 surfaces consume the resolver and chain primitives — and by risk sequencing: 12 of 18 identified pitfalls manifest in Phase 1. The hardest single primitive is the transitive blocker chain flattener; it must be deterministic graph code (not LLM-driven) or the Situation Room signature feature (reduce a 6-link chain to one human action) will produce wrong terminals and destroy trust.",
"",
"The largest cross-cutting risk is the same-origin trust model: plugin UI runs as same-origin trusted JavaScript in the host page. Manifest capabilities gate worker RPC but do not prevent the UI bundle from calling Paperclip HTTP APIs directly. This is the documented platform model, not a design failure to fix. Supply chain discipline and bridge-only code patterns (usePluginData/usePluginAction, ESLint rule against raw fetch, pinned lockfile, no postinstall scripts) must be established on day 1 of Phase 1 before any other code is merged.",
"",
"---",
"",
"## Cross-Cutting Signals (confirmed independently by multiple researchers)",
"",
"These items appeared in two or more research files without coordination. Highest signal. Must appear loudly in SPEC.md.",
"",
"1. **Default branch is master, not main.** All four researchers confirmed this by hitting live URLs. Any downstream docs, CI scripts, or workflow files referencing main (including PROJECT.md and PRIOR-DECISIONS.md) must be corrected before Phase 1.",
"",
"2. **Per-user opt-in is not a host feature.** PLUGIN_SPEC section 8 has no per-user install toggle and no user scope in plugin_state (scope_kind enum: instance | company | project | project_workspace | agent | issue | goal | run — no user). Clarity Pack must implement opt-in in its own clarity_user_prefs table via database.namespace.migrate. Default absence of a row = opted out. Never write a default ON row. Gate every surface render on the toggle before any surface ships.",
"",
"3. **Same-origin trust model is the largest footgun.** Plugin UI runs as same-origin trusted JS. Manifest capabilities gate worker calls but NOT direct UI fetch. Mandatory mitigations (all Phase 1, day 1): bridge-only via usePluginData/usePluginAction; ESLint rule failing CI on raw fetch to Paperclip host paths; pinned pnpm-lock.yaml; no postinstall scripts; monthly pnpm audit.",
"",
"4. **Editor-Agent must be a managed agent.** Declare in manifest agents[], reconcile per-company via ctx.agents.managed.reconcile(). Satisfies coexistence guarantee #4 (governance parity) for free: inherits Paperclip heartbeat, budget caps, pause/terminate, and audit log automatically. A custom setInterval daemon bypasses all of these. Never use setInterval in setup().",
"",
"5. **Bulletin scheduling needs DST-safe next-due-at.** Do not rely on a bare cron string interpreted as UTC. Worker reads a next_due_at timestamp from plugin_state, computes it using date-fns-tz or luxon in America/New_York. Idempotent fire: if next_due_at has already been processed, no-op. CI must test both DST transitions.",
"",
"6. **Situation Room recompute = worker materializer job + UI poll.** Use usePluginData with refetchInterval. Worker job writes a snapshot row each minute; UI reads the latest snapshot row. Pause polling when tab is hidden (document.visibilityState). Use BroadcastChannel to elect one leader tab per browser. Cadence discrepancy: PROJECT.md says 60s; mockup says 30s. SPEC.md must resolve this before Phase 1 plan.",
"",
"7. **comment.created exists in section 16; comment.updated does not.** Chat message edits must be modeled as new comments with supersedes-links (append-only). Confirm this interpretation before Phase 3 design is locked.",
"",
"8. **One bundle, many slots.** Never split Clarity Pack into separate plugins per surface. The kitchen-sink example ships 13 contribution points from one manifest. Splitting quadruples install ceremony and forces re-implementation of every shared primitive.",
"",
"9. **Stack is non-negotiable.** React 19 (peer-only, never bundled), TS ^5.7.3, esbuild ^0.27.3, ESM-only, Node >=20, shadcn new-york/neutral/lucide. Do not ship Tailwind — inherit host CSS. These are FORCED by Paperclip plugin contract.",
"",
"10. **MCP is solved.** @paperclipai/mcp-server@^0.1.0 exposes all Editor-Agent read needs. Run via npx -y @paperclipai/mcp-server. The plugin does not import the MCP server as a library; the adapter launches it as a child stdio process.",
"",
"11. **Phase 1 build order is dictated by shared primitives.** src/shared/reference-resolver.ts and src/shared/blocker-chain.ts must exist before Reader view or Situation Room can be built. 12 of 18 pitfalls land in Phase 1.",
"",
"---",
"",
"## Key Findings",
"",
"### Recommended Stack",
"",
"The Paperclip plugin contract makes the following non-negotiable.",
"",
"**Top 3 FORCED stack pins:**",
"- @paperclipai/plugin-sdk@^1.0.0 — sole supported plugin API; everything else is built on it",
"- React ^19.0.0 as peer dependency (never bundled) — host externalizes it; bundling breaks hook singletons and the bridge",
"- esbuild ^0.27.3 with externals for react, react-dom, react/jsx-runtime, @paperclipai/plugin-sdk/ui, @paperclipai/plugin-sdk/ui/hooks — host singletons; bundling any of these breaks the bridge",
"",
"Additional forced choices: TypeScript ^5.7.3, ESM-only (\"type\": \"module\"), Node >=20, shadcn new-york/neutral/cssVariables/lucide (match ui/components.json exactly), database.migrationsDir + plain SQL files (not Drizzle Kit — Drizzle is a host concern), @paperclipai/mcp-server@^0.1.0 for Editor-Agent reads.",
"",
"The paperclipPlugin field in package.json pointing to dist/manifest.js, dist/worker.js, and dist/ui/ is the host discovery mechanism. Without it, paperclipai plugin install fails silently.",
"",
"### Expected Features",
"",
"**Top 3 TABLE STAKES per surface:**",
"",
"Surface 1 (Reader View): (1) plain-English TL;DR at top with freshness stamp, (2) inline reference chips with status resolution, (3) resolved-reference quote cards with substantive excerpt — not just title+status; this is the no-rabbit-hole payoff",
"",
"Surface 2 (Situation Room): (1) live state per agent with age timestamps, (2) transitively-resolved blocker chain ending in one human action — signature differentiator and hardest primitive, (3) critical-path strip across the whole org",
"",
"Surface 3 (Bulletin): (1) scheduled 06:30 ET delivery with DST-safe cadence, (2) action/decision inbox at top, (3) numbers from SQL queries not LLM generation — two-pass compile with verifier",
"",
"Surface 4 (Chat): (1) real-time message UI with per-employee threads, (2) persistence as issue comments — canonical, never plugin-table storage, (3) hybrid persistence: real-time UI + durable as ordinary issue comments (coexistence #5 hard constraint)",
"",
"**Shared primitives (build first — all surfaces depend on these):**",
"1. Reference resolver (src/shared/reference-resolver.ts) — batch-resolves IDs, used by all four surfaces",
"2. Blocker chain flattener (src/shared/blocker-chain.ts) — deterministic DFS, terminal taxonomy, cycle detection",
"3. TL;DR types + tldr_cache schema — shared between worker and UI",
"4. State pill + ref chip + theme tokens (src/ui/primitives/)",
"5. Opt-in accessor + clarity_user_prefs table — gates every surface render",
"",
"Defer to Phase 4 / v2+: AC auto-status, group threads, XLSX/PDF full-fidelity preview, multi-recipient bulletin, email/Slack distribution.",
"",
"### Architecture Approach",
"",
"Clarity Pack is one TypeScript package with one manifest, one UI bundle (ESM, many named React exports), and one out-of-process Node worker over JSON-RPC stdio. All four surfaces contribute slots from the same manifest. The worker registers data handlers (ctx.data.register), action handlers (ctx.actions.register), jobs (background housekeeping), and routines (visible board tasks like the bulletin compile). The Editor-Agent is declared in agents[] and reconciled per-company via ctx.agents.managed.reconcile() — not a custom daemon.",
"",
"**Major components:**",
"1. UI bundle (src/ui/index.tsx) — pure presentation + bridge calls; one ESM bundle exporting one React component per slot by name",
"2. Worker (src/worker.ts) — out-of-process Node; registers data/action/job/route handlers; never imports from src/ui/",
"3. Editor-Agent — declared in manifest agents[]; reconciled per-company; compiles TL;DRs, critical-path narratives, bulletins; standard Paperclip employee with all governance applied automatically",
"4. Plugin DB namespace (plugin_clarity_pack_<hash>) — tldr_cache, situation_snapshots, bulletin_issues, chat_topics, clarity_user_prefs; chat message content lives in public.issue_comments (canonical per Decision #1)",
"5. Shared primitives (src/shared/) — no host imports; consumed by both worker and UI; reference resolver and blocker chain are the architecturally critical ones",
"",
"Data flow: UI calls usePluginData(key, params) -> bridge -> worker handler -> reads plugin namespace DB or Paperclip core tables -> returns JSON -> React renders. Write flow: UI calls usePluginAction(key) -> worker -> ctx.issue.comments.create or ctx.db.execute -> audit log -> domain event -> Editor-Agent picks up on next heartbeat.",
"",
"Reader view slot: detailTab with entityTypes: [issue] per PLUGIN_SPEC section 10.1. Fall back to taskDetailView only if testing reveals it renders in a more prominent position. Resolve in Phase 1 SPEC.md (see Conflicts).",
"",
"Chat real-time updates: usePluginStream subscribed to issue.comment.created filtered to the current chat-issue ID. Poll path is wrong for chat (sub-second latency needed); streams are right here.",
"",
"### Critical Pitfalls",
"",
"**Top 3 that MUST be addressed in Phase 1:**",
"",
"1. **Same-origin trust model bypass (Pitfall 3)** — plugin UI can call Paperclip HTTP APIs directly, bypassing capability gates. Prevention: bridge-only (usePluginData/usePluginAction), ESLint rule failing CI on raw fetch to host paths, pinned lockfile, no postinstall scripts. Cheapest to enforce on day 1; most expensive to fix retroactively.",
"",
"2. **Editor-Agent runaway cost + self-loop (Pitfall 6)** — TL;DR regen writes to issue -> issue.updated fires -> TL;DR regen triggers again. Prevention: filter actor_type=plugin AND actor_id=clarity-pack-editor-agent from event triggers (section 16.1); hard max_tokens per LLM call; idempotency key on (surface, scope_id, content_hash); circuit breaker on 3 consecutive failures; cycle detection in chain resolver.",
"",
"3. **Opt-in toggle does not gate rendering (Pitfall 5)** — detailTab slot appears for all users because the host mounts tabs from the manifest. Prevention: server-side opt-in check in every getData and performAction handler; tab renders Enable Clarity Pack CTA when opted out; absence of clarity_user_prefs row = default OFF.",
"",
"Additional Phase 1 pitfalls that cannot be deferred: CSS bleed-through (Pitfall 4 — scope all styles to [data-clarity-surface]); N+1 reference resolution (Pitfall 12 — batch resolver); wrong blocker chain terminal (Pitfall 13 — deterministic DFS, LLM writes prose only); polling thundering herd (Pitfall 7 — visibility guard + BroadcastChannel + content-hash cache); SPA navigation (Pitfall 16 — useHostNavigation().linkProps(), lint rule); idempotent event handlers (Pitfall 15 — upsert by deterministic key); plugin lifecycle awareness (Pitfall 1 — polling stops on WORKER_UNAVAILABLE).",
"",
"---",
"",
"## Implications for Roadmap",
"",
"### Phase 1: Scaffold + Primitives + Reader View + Situation Room",
"",
"**Rationale:** Both Phase 1 surfaces share the same primitives. Building them together validates the primitives under two rendering contexts. 12 of 18 pitfalls land here; hardening precedes feature richness.",
"",
"**Delivers:** Installable plugin with Reader view and Situation Room, Editor-Agent skeleton producing TL;DRs and critical-path narratives, all shared primitives, opt-in gate, coexistence guarantees 1-4 verified.",
"",
"**Internal build order (strict — each step unblocks the next):**",
"1. Plugin scaffold: manifest.ts, worker.ts skeleton, esbuild configs, paperclipai plugin install works locally",
"2. ESLint rules + CSS scope convention + lifecycle-aware poll primitive (day-1, pre-any-feature)",
"3. Theme tokens + state pill + ref chip shell (src/ui/primitives/)",
"4. Reference resolver (src/shared/reference-resolver.ts) + batch worker handler",
"5. Blocker chain flattener (src/shared/blocker-chain.ts) + cycle detection + terminal taxonomy",
"6. Editor-Agent skeleton: agents[] declaration, reconcile, TL;DR compile with idempotency + self-loop filter + token cap + circuit breaker",
"7. Reader view tab (detailTab slot): TL;DR strip, inline ref chips, ref-card with quote, AC checklist (manual v1), activity timeline, breadcrumb, right-rail blocker panel",
"8. Situation Room page (page slot): agent grid, state pills, now-doing, blocker chain, critical-path strip, artifact shelf, 60s poll with dedupe + visibility guard + BroadcastChannel",
"9. Settings page + opt-in gate: clarity_user_prefs table, set-opt-in action, useOptIn hook, CTA on opted-out surfaces",
"10. Coexistence verification checklist (before any merge to main)",
"",
"**Must resolve in Phase 1 SPEC.md before code:**",
"- Auto-refresh cadence (60s vs 30s)",
"- Reader view slot type (detailTab vs taskDetailView — test on live instance first)",
"- Plugin-owned migrations vs plugin_state only (see Conflicts)",
"- Full capability list with rationale (over-declare to avoid upgrade_pending later)",
"",
"**Research flag:** Needs /gsd:research-phase for slot type conflict and migrations conflict. Heartbeat cadence must be verified empirically. Install command exact form must be verified via pnpm paperclipai plugin --help.",
"",
"### Phase 2: Daily Bulletin",
"",
"**Rationale:** Reuses Phase 1 primitives and adds one new Editor-Agent routine. New complexity: editorial voice, two-pass verification, DST-safe scheduling, lineage threads.",
"",
"**Delivers:** Scheduled 06:30 ET editorial digest with action inbox, department sections, standing numbers, lineage threads, errata workflow.",
"",
"**Key additions:** compile-bulletin.ts routine with two-pass compile (draft -> verifier -> publish); bulletin_issues + bulletin_drafts tables for transactional compile; DST-safe next-due-at via date-fns-tz/luxon in America/New_York; numbers from SQL queries (never LLM-generated); errata as first-class item type; explicit failed-compile banner.",
"",
"**Must avoid:** Pitfalls 9 (DST drift), 10 (hallucinated numbers), 14 (transcription drift), 6 (self-loop on retry).",
"",
"**Research flag:** Verify cron timezone interpretation in PLUGIN_SPEC section 17 before Phase 2 design is locked.",
"",
"### Phase 3: Employee Chat",
"",
"**Rationale:** Depends on all Phase 1 primitives and requires usePluginStream wiring — a new architectural primitive. Hybrid persistence model is the highest-risk single architectural commitment and should be proven only after Phase 1 validates issue-comment persistence.",
"",
"**Delivers:** Per-employee x per-topic chat with hybrid persistence, reasoning panel, promote-to-task, one-click decision messages, context rail, global search.",
"",
"**Key additions:** chat_topics table (CHT-NN -> issue ID mapping only; message content lives in public.issue_comments); usePluginStream subscription to issue.comment.created filtered by chat-issue ID; chat.send action writing to ctx.issue.comments.create (canonical); idempotency keys per message (client-generated message_uuid); edits as append-with-supersedes; optimistic render with rollback on send failure; coexistence test (disable plugin -> messages still render as classic comments).",
"",
"**Must confirm before Phase 3:** comment.updated event existence in section 16; usePluginStream direct host event subscription scope.",
"",
"**Must avoid:** Pitfalls 11 (dual-write divergence), 15 (non-idempotent handlers), 7 (thundering herd).",
"",
"### Phase 4: Polish + Distribution",
"",
"**Delivers:** AC auto-status upgrade, XLSX/PDF preview registry, group threads (multi-agent), npm publish polish, accessibility audit, Clipmart readiness.",
"",
"**Standard patterns — skip research-phase:** A11y, npm publish, lockfile audit are well-documented.",
"",
"### Phase Ordering Rationale",
"",
"- **Primitive dependencies:** Reader view and Situation Room both block on reference resolver and blocker chain. Bulletin blocks on TL;DR types. Chat blocks on issue-comment persistence proven by Phase 1.",
"- **Risk sequencing:** 12 of 18 pitfalls land in Phase 1. Getting the scaffold, trust model, opt-in gate, poll primitive, and Editor-Agent skeleton right first is the single highest-leverage risk reduction.",
"- **Incremental architectural validation:** Each phase introduces exactly one new architectural primitive — Phase 1 validates managed agent + detailTab integration, Phase 2 validates cron routines, Phase 3 validates stream wiring, Phase 4 validates public release hardening.",
"",
"### Research Flags",
"",
"Needs /gsd:research-phase before Phase 1 detailed planning:",
"- Reader view slot type conflict (detailTab vs taskDetailView) — requires live test on running Paperclip instance",
"- Plugin-owned migrations conflict — must decide before writing first migration",
"- Heartbeat cadence specifics — verify empirically before TL;DR freshness SLA is set",
"- Install command exact form — verify by running pnpm paperclipai plugin --help",
"",
"Needs verification before Phase 2: cron timezone interpretation in PLUGIN_SPEC section 17",
"",
"Needs verification before Phase 3: usePluginStream direct host event subscription scope; comment.updated event existence in section 16",
"",
"Standard patterns (skip research-phase): Phase 4 polish — a11y, npm publish, lockfile audit",
"",
"---",
"",
"## Conflicts Requiring SPEC.md Resolution",
"",
"These must be resolved before Phase 1 code is written. The roadmap must not inherit these as ambiguity.",
"",
"### Conflict 1: Plugin-owned migrations vs plugin_state/plugin_entities only",
"",
"**Option A (Architecture + Stack researchers):** Use database.migrationsDir + plugin namespace (plugin_clarity_pack_<hash>) for custom tables. Supported by PLUGIN_AUTHORING_GUIDE.md, plugin-orchestration-smoke-example migrations, and the running SDK (PR #5205). PLUGIN_SPEC.md section 21.5 text says out of scope but the implementation is ahead of the spec.",
"",
"**Option B (Pitfalls researcher):** Stay on plugin_state/plugin_entities with embedded schemaVersion because migration bugs (partial apply, upgrade divergence) are documented footguns and the formal spec still says out of scope.",
"",
"**Recommended default:** Option A. plugin_state is a key-value store that cannot express the relational structure needed (batch reference resolution, blocker chain traversal, global chat search). The additive-only constraint is satisfied by namespace isolation — the plugin cannot mutate public.*.",
"",
"**Deciding question for SPEC.md:** Does pnpm paperclipai plugin install on a fresh local Paperclip clone successfully apply migrations/001_init.sql scoped to the plugin namespace? Verify in Phase 1.0 with a minimal migration before any feature work. If it fails, fall back to Option B with schemaVersion-tagged plugin_state.",
"",
"### Conflict 2: Reader view slot identity (taskDetailView vs detailTab)",
"",
"**Evidence for detailTab:** PLUGIN_SPEC section 10.1 lists it as canonical. plugin-kitchen-sink-example uses { type: detailTab, entityTypes: [issue] }.",
"",
"**Evidence for taskDetailView:** plugin-orchestration-smoke-example uses { type: taskDetailView, entityTypes: [issue] }. It may render in a more prominent position.",
"",
"**Resolution:** Use detailTab as primary. In Phase 1.0, run against a live Paperclip instance and verify which slot renders in the position the mockup expects (next to classic tabs). Remove the other. Decision must be in Phase 1 SPEC.md before Reader view implementation begins.",
"",
"### Conflict 3: Situation Room auto-refresh cadence",
"",
"**PROJECT.md** says 60s. **Mockup** says auto-refresh 30s.",
"",
"**Resolution:** Decide in Phase 1 SPEC.md. Recommendation: 60s initially (matches locked Decision #2, cheaper), exposed as a configurable value in instanceConfigSchema. Document the 30s mockup as a visual aspiration, not a hard requirement.",
"",
"---",
"",
"## Confidence Assessment",
"",
"| Area | Confidence | Notes |",
"| Stack | HIGH | All pins fetched directly from paperclipai/paperclip@master source files. No inference. |",
"| Features | HIGH | Grounded in four non-throwaway HTML mockups + competitive analysis. |",
"| Architecture | HIGH | Canonical example plugins inspected verbatim. MEDIUM on heartbeat cadence and MCP adapter wiring. |",
"| Pitfalls | HIGH (catalog), MEDIUM (severity) | 18 pitfalls with spec citations and phase assignments. |",
"",
"**Overall confidence:** HIGH on what to build and how. MEDIUM on three implementation questions requiring live testing in Phase 1.0.",
"",
"### Gaps to Address During Planning",
"",
"1. **Heartbeat cadence:** doc/execution-semantics.md does not quantify frequency. Phase 1.4 must verify empirically whether TL;DR freshness SLA is achievable or whether a wakeup trigger from issue.updated event is needed.",
"",
"2. **plugin_state user scope absent:** If migrations conflict resolved as Option B, use instance scope with user_id encoded in state_key for the opt-in prefs.",
"",
"3. **Work-products availability for chat attachments:** PROJECT.md lists Artifacts & Work Products as unbuilt. Phase 3 must pre-flight ctx.actions.checkCapability and disable the attach button with explicit error if absent.",
"",
"4. **usePluginStream direct host event subscription:** Unverified for Phase 3. Verify in Phase 1 by running kitchen-sink in dev mode and testing whether usePluginStream can subscribe to issue.comment.created without a worker re-emit intermediary.",
"",
"5. **MCP adapter to managed-agent wiring:** Stack researcher flags MEDIUM confidence on the exact handshake between the claude_local/process adapter config and an MCP server child stdio process. Verify by tracing the adapter handshake before Phase 1.4.",
"",
"---",
"",
"## Sources",
"",
"### Primary (HIGH confidence — fetched from paperclipai/paperclip@master, 2026-05-07)",
"",
"- doc/plugins/PLUGIN_SPEC.md — manifest shape, capabilities, install command, trust model, process model, event types",
"- doc/plugins/PLUGIN_AUTHORING_GUIDE.md — slot types, agents/routines/database manifest fields, ctx.* APIs, bridge hooks",
"- packages/plugins/examples/plugin-kitchen-sink-example/ — canonical multi-surface plugin (13 slots, verbatim)",
"- packages/plugins/examples/plugin-orchestration-smoke-example/ — database namespace + migrations + apiRoutes (verbatim)",
"- packages/plugins/examples/plugin-file-browser-example/ — detailTab + settingsPage + instance config (verbatim)",
"- ui/package.json, ui/components.json, ui/tsconfig.json — host version pins, shadcn config",
"- packages/plugins/sdk/package.json, packages/plugins/sdk/src/bundlers.ts — SDK exports, build presets",
"- packages/mcp-server/package.json, packages/mcp-server/README.md — MCP tool list, auth env, invocation",
"- doc/SPEC.md, doc/SPEC-implementation.md, doc/DATABASE.md — core entities, heartbeat, REST API",
"- Paperclip PRs #4738, #5205; Issues #5123, #4954, #4952, #5096",
"",
"### Secondary (MEDIUM confidence)",
"",
"- Mockups: sketches/paperclip-fix-task-detail.html, sketches/paperclip-fix-situation-room.html, sketches/paperclip-fix-bulletin.html, sketches/paperclip-fix-employee-chat.html",
"- Linear, Temporal Web, LangSmith, Slack AI Recap, AutoGen Studio — competitive analysis",
"- Nature 2025: hallucination detection and mitigation framework for faithful summarization",
"- Cloudflare Sept 12 2025 outage post-mortem — thundering herd pattern",
"- node-cron, Sentry, Red Hat — DST cron bug documentation",
"",
"### Tertiary (LOW confidence — needs Phase 1 verification)",
"",
"- doc/execution-semantics.md — heartbeat cadence specifics (paraphrased, not quantified)",
"- doc/CLI.md — omits plugin install command; PLUGIN_SPEC section 8.2 is source of truth",
"- MCP adapter to managed-agent wiring — inferred from authoring guide, not traced end-to-end",
"",
"---",
"*Research completed: 2026-05-07*",
"*Ready for roadmap: yes, pending resolution of 3 conflicts in Phase 1 SPEC.md*",
];

fs.writeFileSync(DEST, lines.join("\n"), "utf8");
console.log("Written " + lines.length + " lines to SUMMARY.md");
