// src/worker/bulletin/bulletin-gloss.ts
//
// Plan 07-05 (Phase 7 ITEM 5) — D-I5-02 view-driven per-bulletin GLOSS compile.
//
// Each surviving lineage thread (after filterLineageThreads) gets a one-line
// plain-English gloss ("what this means for you, a busy founder") generated by
// the Editor-Agent (LLM). The gloss compiles in the SAME view-driven engine the
// TL;DR uses (editor.ts driveTldrCompileStep), in a VALID HTTP-request scope (the
// bulletin.byCycle data handler) — NOT the scope-dead compile-bulletin scheduled
// job (paperclipai@2026.525.0 PR #6547). It is cached in the EXISTING tldr_cache
// table (surface='bulletin', scopeId='bulletin-gloss:<cycle>') — NO new
// migration. ONE agent operation per view emits a JSON {threadId→gloss} MAP (not
// N tasks), keyed by a content-hash of the FILTERED thread set so it recompiles
// ONLY when the surviving threads change.
//
// GRACEFUL DEGRADE (LOCKED): a paused/unresolvable Editor-Agent → threads render
// WITHOUT a gloss (gloss:null) — NEVER an error, and we NEVER auto-resume a
// paused agent on a passive Bulletin view (resume is an explicit operator
// action — governance parity). The step NEVER throws: every host call is wrapped
// so a hiccup degrades to gloss:null + a non-error status.
//
// NO_UUID_LEAK: the only thread identity injected into the prompt is the opaque
// composite `thread.id` (e.g. `<issueId>:<actor>:<ts>`) used solely as the map
// key — NOT a bare host UUID rendered to the user. The owner UUID for the chat
// link is set by the HANDLER (bulletin-by-cycle.ts), never here, never rendered.
//
// Instance-agnostic: NO 'BEAAA' literal — the prompt is generic.

import type { LineageThread } from '../../shared/types.ts';
import {
  EDITOR_AGENT_KEY,
  resolveEditorAgentId,
  type TldrViewDriverCtx,
} from '../agents/editor.ts';
import {
  tldrContentHash,
  finalizeTldr,
  type CompileTldrCtx,
} from '../agents/compile-tldr.ts';
import { getTldrByScope } from '../db/tldr-cache.ts';
import {
  startAgentTask,
  pollAgentTaskResult,
} from '../agents/agent-task-delivery.ts';

/** The ctx the gloss step needs — the SAME shape as the TL;DR view driver plus
 *  the cache primitives' ctx (db.execute for finalizeTldr). The bulletin.byCycle
 *  handler satisfies this via its existing `ctx as unknown as CompileBulletinCtx`
 *  cast (which already carries db/issues/agents). */
export type BulletinGlossCtx = TldrViewDriverCtx & CompileTldrCtx;

export type BulletinGlossStepResult = {
  threads: LineageThread[];
  /**
   * - `glossed`     — a fresh gloss map is applied (cache hit or just consumed).
   * - `compiling`   — the Editor-Agent is working; poll again on the next view.
   * - `paused`      — the Editor-Agent is paused; it won't compile until an
   *                   explicit operator resume (we never auto-resume on a
   *                   passive Bulletin view).
   * - `unavailable` — no Editor-Agent could be resolved (can't start a compile).
   */
  status: 'glossed' | 'compiling' | 'paused' | 'unavailable';
};

const GLOSS_SCOPE_PREFIX = 'bulletin-gloss:';

/** Build the canonical content-hash input for a filtered thread set so the gloss
 *  recompiles ONLY when the surviving threads change (a new edition, or the
 *  filter output shifts) — fixed field ordering, ids + node signatures only. */
function canonicalThreadBody(threads: LineageThread[]): string {
  const sig = threads.map((t) => ({
    id: t.id,
    nodes: (Array.isArray(t.nodes) ? t.nodes : []).map((n) => ({
      name: typeof n?.name === 'string' ? n.name : '',
      detail: typeof n?.detail === 'string' ? n.detail : '',
      time: typeof n?.time === 'string' ? n.time : '',
    })),
  }));
  return JSON.stringify(sig);
}

/** The gloss PROMPT — instance-agnostic. Instructs STRICT JSON {id→sentence}. */
function buildGlossPrompt(threads: LineageThread[]): string {
  const lines = threads.map((t) => {
    const detail = (Array.isArray(t.nodes) ? t.nodes : [])
      .map((n) => `${typeof n?.name === 'string' ? n.name : ''}: ${typeof n?.detail === 'string' ? n.detail : ''}`.trim())
      .join(' → ');
    return `- id "${t.id}": ${detail}`;
  });
  return [
    'You are the Editorial Desk compiling the Daily Bulletin lineage section.',
    'For EACH thread below, write a SINGLE plain-English sentence describing what',
    'this work means for you, a busy founder — concrete and concise, no jargon.',
    '',
    'Threads:',
    ...lines,
    '',
    'Return STRICT JSON ONLY: an object mapping each thread id to its one-line',
    'sentence, e.g. {"<id>":"<sentence>"}. No prose, no markdown, no code fence',
    'around the JSON. Do not include any UUIDs or internal identifiers in the',
    'sentences — describe the work, not the ids.',
  ].join('\n');
}

/** Apply a parsed {id→gloss} map to the threads (missing key → null). */
function applyGlosses(threads: LineageThread[], map: Record<string, unknown> | null): LineageThread[] {
  return threads.map((t) => {
    const v = map ? map[t.id] : null;
    return { ...t, gloss: typeof v === 'string' && v.trim().length > 0 ? v : null };
  });
}

/** Parse the agent's JSON-map body defensively (parse-throw / non-object → null). */
function parseGlossMap(body: string): Record<string, unknown> | null {
  try {
    const parsed = JSON.parse(body);
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
    return null;
  } catch {
    return null;
  }
}

const NULL = null;
function nullGlosses(threads: LineageThread[]): LineageThread[] {
  return threads.map((t) => ({ ...t, gloss: NULL }));
}

/**
 * D-I5-02 — advance the per-bulletin gloss compile by exactly one step, in the
 * CALLER's (valid HTTP-request) invocation scope. Mirrors editor.ts
 * driveTldrCompileStep: cache-hit → apply instantly; cache-miss → resolve the
 * Editor-Agent, PAUSED-check (no auto-resume), startAgentTask + ONE poll, ready
 * → finalize the JSON map into the cache + apply. NEVER throws.
 */
export async function driveBulletinGlossStep(
  ctx: BulletinGlossCtx,
  args: { companyId: string; cycleNumber: number; threads: LineageThread[] },
): Promise<BulletinGlossStepResult> {
  const { companyId, cycleNumber } = args;
  const threads = Array.isArray(args.threads) ? args.threads : [];
  if (threads.length === 0) {
    return { threads: [], status: 'glossed' };
  }

  const scopeId = `${GLOSS_SCOPE_PREFIX}${cycleNumber}`;
  const contentHash = tldrContentHash({
    surface: 'bulletin',
    scopeId,
    inputs: { body: canonicalThreadBody(threads), comments: [], refs: [] },
  });

  // CACHE CHECK — a row with a matching content_hash short-circuits (no compile).
  try {
    const cached = await getTldrByScope(ctx, 'bulletin', scopeId);
    if (cached && cached.content_hash === contentHash) {
      return { threads: applyGlosses(threads, parseGlossMap(cached.body)), status: 'glossed' };
    }
  } catch (e) {
    ctx.logger?.warn?.(`bulletin-gloss: cache read failed: ${(e as Error).message}`, { companyId });
  }

  // CACHE MISS — resolve the Editor-Agent (op-issue discovery, NO dead reconcile
  // loop — same helper the TL;DR view driver uses in its valid request scope).
  const editorAgentId = await resolveEditorAgentId(ctx, companyId);
  if (!editorAgentId) {
    ctx.logger?.info?.('bulletin-gloss: no Editor-Agent resolvable — no gloss', { companyId, cycleNumber });
    return { threads: nullGlosses(threads), status: 'unavailable' };
  }

  // PAUSED check (mirror editor.ts) — a paused agent never processes the compile;
  // we do NOT auto-resume on a passive Bulletin view. Render without a gloss.
  try {
    const agent = await ctx.agents?.get?.(editorAgentId, companyId);
    if (agent && (agent.status === 'paused' || agent.pausedAt != null)) {
      ctx.logger?.info?.('bulletin-gloss: Editor-Agent paused — not starting (no auto-resume)', {
        companyId,
        cycleNumber,
      });
      return { threads: nullGlosses(threads), status: 'paused' };
    }
  } catch {
    /* status unknown — fall through and attempt the compile */
  }

  // START (or reuse the in-flight op via idempotency) + ONE immediate poll.
  let operationIssueId: string;
  try {
    const started = await startAgentTask(ctx, {
      agentId: editorAgentId,
      companyId,
      operationKind: 'bulletin-gloss',
      operationId: `bulletin-gloss-${cycleNumber}`,
      title: `Compile bulletin lineage gloss — cycle ${cycleNumber}`,
      prompt: buildGlossPrompt(threads),
    });
    operationIssueId = started.operationIssueId;
  } catch (e) {
    ctx.logger?.warn?.(`bulletin-gloss: startAgentTask failed: ${(e as Error).message}`, {
      companyId,
      cycleNumber,
    });
    return { threads: nullGlosses(threads), status: 'compiling' };
  }

  let poll: { status: 'ready'; body: string } | { status: 'pending' };
  try {
    poll = await pollAgentTaskResult(ctx, {
      operationIssueId,
      companyId,
      operationKind: 'bulletin-gloss',
      agentId: editorAgentId,
    });
  } catch (e) {
    ctx.logger?.warn?.(`bulletin-gloss: poll failed: ${(e as Error).message}`, { companyId, cycleNumber });
    return { threads: nullGlosses(threads), status: 'compiling' };
  }
  if (poll.status !== 'ready') {
    return { threads: nullGlosses(threads), status: 'compiling' };
  }

  // READY — parse the JSON map defensively. A non-JSON / non-object body → all
  // null glosses (still finalize the raw body so the next view is a cache-hit and
  // we don't re-spawn endlessly; finalizeTldr validates body is a non-empty
  // string ≤ 8000 chars, which the agent body satisfies).
  const map = parseGlossMap(poll.body);
  try {
    await finalizeTldr(ctx, {
      surface: 'bulletin',
      scopeId,
      contentHash,
      body: poll.body,
      agentKey: EDITOR_AGENT_KEY,
      agentId: editorAgentId,
      companyId,
      truncated: false,
    });
  } catch (e) {
    // A validation/breaker failure must not fail the read — degrade to no-gloss.
    ctx.logger?.warn?.(`bulletin-gloss: finalize failed: ${(e as Error).message}`, { companyId, cycleNumber });
    return { threads: map ? applyGlosses(threads, map) : nullGlosses(threads), status: 'glossed' };
  }

  // Mark the operation issue done (best-effort) so a later edition starts fresh.
  try {
    await ctx.issues.update(operationIssueId, { status: 'done' }, companyId);
  } catch (e) {
    ctx.logger?.info?.('bulletin-gloss: could not mark op issue done (non-fatal)', {
      operationIssueId,
      reason: (e as Error).message,
    });
  }

  return { threads: applyGlosses(threads, map), status: 'glossed' };
}
